import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Sidehug from '../components/Sidehug'
import MyClass from '../components/MyClass'
import { useState } from 'react'
import Modal from '../components/Modal'

import { UserContext } from '../UserContext'
import {useContext} from 'react';
export default function Home() {

  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main className={styles.main}>
  //       <h1 className={styles.title}>
  //         Welcome to <a href="https://nextjs.org">Next.js!</a>
  //       </h1>

  //       <p className={styles.description}>
  //         HI
  //         <code className={styles.code}>pages/index.js</code>
  //       </p>

  //       <div className={styles.grid}>
  //         <a href="https://nextjs.org/docs" className={styles.card}>
  //           <h2>Documentation &rarr;</h2>
  //           <p>Find in-depth information about Next.js features and API.</p>
  //         </a>

  const [showModal, setShowModal] = useState(false);
  const handleModal=()=>{
    setShowModal(prev=>!prev);
  }

  return (
    <div className={styles.home}>
      <Navbar/>
      <Sidehug/>
      <h4>My classes</h4> 
      <div className={styles.class}>
        <MyClass/>
        <MyClass/>
        {/* <MyClass/>
        <MyClass/> */}
      </div>
      <button className='button' onClick={handleModal}>Im Modal</button>
      <Modal showModal={showModal} setShowModal={setShowModal}/>
    </div>
  )
}
